### ISSUE TITLE
user management beyond user self-registration

### ISSUE THREAD

**Issue by JosefAssad** [deepsense-ai/seahorse#1]
When authorisation is turned on (I'm using the docker-compose from the distribution served from deepsense.ai FWIW), any user can self-register.

I think it would be smart to keep this, but hide it behind a configuration toggle which changes Seahorse's behavior with respect to user management.

Some Seahorse users might prefer to be able to control who can and cannot access Seahorse instances they have deployed, if they happen to be in a public cloud, or if it's deployed on private infrastructure, there may be internal users who should and should not get access.

A "lowest hanging fruit" short term solution might be to hide the option behind a toggle and provide Seahorse admins with facilities for manually registering users.

A longer term solution would probably involve looking into what options for user management are available and desired in the Seahorse actual and potential userbase.

**Comment by lazers378** [comment]
It is closed, but is there user management ? I can only see self registration.
