### ISSUE TITLE
Allow categories for custom blocks

### ISSUE THREAD

**Issue by rabejens** [deepsense-ai/seahorse#15]
Currently all custom blocks created with the SDK appear in the "User Defined" category. It would be nice if it was possible to define a category as well.

**Comment by jaroslaw-osmanski** [comment]
Thank you for suggesting this enhancement. We are focusing on fixing bugs right now, so we won't work on this feature now.

We're open for Pull Requests though. Here is part of code where category is hardcoded: `https://github.com/deepsense-ai/seahorse/blob/master/seahorse-workflow-executor/deeplang/src/main/scala/ai/deepsense/deeplang/refl/CatalogScanner.scala#L99` Similar change should be added in seahorse-sdk code.

**Comment by metasim** [comment]
Implementation idea:  Allow `ai.deepsense.deeplang.refl.Register` to have two optional parameters: a `groupName: String` and `priority: Int`, to be used by the frontend to group and order `DOperation`s.

**Comment by jaroslaw-osmanski** [comment]
Ability to create categories is provided in newest Seahorse master. Building only SDK won't work as current Seahorse master wasn't released to maven.

To add your categories
- Checkout Seahorse master
- go seahorse-sdk-example folder
- read README.md
