### ISSUE TITLE
Lazily evaluate Reports or provide ability to turn off

### ISSUE THREAD

**Issue by metasim** [deepsense-ai/seahorse#16]
Both the full and simplified DataFrame `Report`s generated by `ai.deepsense.deeplang.doperables.dataframe.report.DataFrameReportGenerator` call `count` on the `DataFrame`, causing a full upstream evaluation of the `LogicalPlan`. There are instances where this is very costly, and where downstream operations enable the Catalyst Optimizer to reduce the execution cost of the resulting physical plan, as long as intermediate actions are not invoked. While the reports are necessary for interactive inspection of the data at each stage, some workflows can completely hang up a session due to strict evaluation of Report contents.

It would be a great feature to be able to turn off action-invoking report generation in each node.

FWIW, this is what I'm using in custom operations to keep actions from being invoked.

```scala
import ai.deepsense.commons.types.ColumnType
import ai.deepsense.deeplang.doperables.dataframe.DataFrame
import ai.deepsense.deeplang.doperables.dataframe.report.DataFrameReportGenerator
import ai.deepsense.deeplang.doperables.dataframe.report.DataFrameReportGenerator.ReportContentName
import ai.deepsense.deeplang.doperables.report.Report
import ai.deepsense.reportlib.model.{ReportContent, ReportType, Table}
import org.apache.spark.sql
import org.apache.spark.sql.types.StructType

/**
 * Specialization of the Seahorse DataFrame where the report is limited to showing
 * the schema.
 */
class SimpleReportDataFrame(override val sparkDataFrame: sql.DataFrame, override val schema: Option[StructType]) extends DataFrame() {
  override def report: Report = {
    val tables = schema.map(schemaTable).toSeq
    Report(ReportContent(
      ReportContentName,
      ReportType.DataFrameSimplified,
      tables
    ))
  }

  def schemaTable(schema: StructType): Table = {
    val values = schema.fields.zipWithIndex.map {
      case (field, index) =>
        val columnName = field.name
        val columnType = field.dataType.simpleString
        List(Some(index.toString), Some(columnName), Some(columnType))
    }.toList

    Table(
      DataFrameReportGenerator.DataSchemaTableName,
      s"Preview of columns and their types in dataset",
      Some(List("Column index", "Column name", "Column type")),
      List(ColumnType.numeric, ColumnType.string, ColumnType.string),
      None,
      values)
  }
}
```

**Comment by rabejens** [comment]
This is possibly related to #14

**Comment by metasim** [comment]
This issue is coming up for us more with built-in nodes, like Join.... the report preemptively invokes an action, even before considering downstream filters which, through logical plan optimization and column pruning, may reduce the amount of data ultimately fetched.

My current thinking is that every node should have an switch (`BooleanParam`) to turn off statistics gathering and row counting (and anything else that might invoke a DataSet/RDD action). Our only recourse now is to not use "big data" during workflow construction.

**Comment by rabejens** [comment]
So you have the problem workflow executions stalling, too? I have not yet managed to get an exported workflow running standalone with the standalone workflow executor - I have to test this some more. If you managed, can you test if executing the workflow stand-alone with a very large data set which gets stuck during the construction will get stuck when executing standalone, too?

**Comment by metasim** [comment]
@rabejens We've not yet gotten standalone mode working with our cluster, but in local mode we end up using all the memory allocated to Docker, and the driver just crashes, and Seahorse only sometimes detects it sometimes (I think because all of Docker gets upset).
