### ISSUE TITLE
Link to Spark UI 

### ISSUE THREAD

**Issue by metasim** [deepsense-ai/seahorse#18]
It would be helpful to to have a link to the Spark web UI in the seahorse front end. In "Local" mode you could have a proxy route to it. In cluster mode you could either a) assume it's on the driver at 4040, or b) have a place in the cluster configuration page to specify the URI.

**Comment by jaroslaw-osmanski** [comment]
Addressed by https://github.com/deepsense-ai/seahorse/pull/90
