### ISSUE TITLE
Use `/usr/bin/env` to select python interpreter in script headers

### ISSUE THREAD

**Issue by metasim** [deepsense-ai/seahorse#19]
The following scripts specifically select `/usr/bin/python` as their interpreter, which is problematic when environments such as Anaconda are used, dependencies are sandboxed, and `python` selected should be what's resolved by the `PATH` variable.

* `utils/api_version.py`
* `deployment/docker-compose/docker-compose.py`
* `build/manage-docker.py`

**Comment by jaroslaw-osmanski** [comment]
Merged fix: https://github.com/deepsense-ai/seahorse/pull/20
