### ISSUE TITLE
Allow SDK use of `ai.deepsense.deeplang.doperables.Transformer`

### ISSUE THREAD

**Issue by metasim** [deepsense-ai/seahorse#23]
`Transformer`  and the associated `TransformerAsOperation` classes serve a useful role in abstracting over the construction of transformers. SDK users can not build against them because the abstract method `Transformer._transform` is marked as `private[deeplang]`. Would the project consider agging it and `_transformSchema` as `protected` instead?

**Comment by metasim** [comment]
I'm happy to submit a PR for this if amenable.

**Comment by jaroslaw-osmanski** [comment]
Please submit a PR. It will be accepted.

**Comment by metasim** [comment]
Turns out that just changing the `private[deeplang]` to `protected` doesn't work, because `TransformerWrapper` and `StringIndexingWrapperModel` call the `_transform` and `_transformSchema` methods directly on the entities they wrap. As best I know, there's no way in Scala to say access is either `protected` or `private[xyz]`.

**Comment by metasim** [comment]
Addressed in #36
