### ISSUE TITLE
Replace "Reflections" with Java ServiceLoader/SPI for SDK.

### ISSUE THREAD

**Issue by metasim** [deepsense-ai/seahorse#30]
IMHO, use of the _Reflections_ library is a liability. It is partially or fully behind issues #11 and #26. I have personal experience with it in past projects where we found it to greatly affect startup time, and clash with instantiation sequencing via Google Guice. It also seems to have a [problematic License](https://github.com/ronmamo/reflections/issues/159), at least when used without forking and changing the license first.

I'd suggest replacing the use of Reflections with the standard Java SPI API, which is quite easy to use, has very low overhead, and doesn't suffer from ClassLoader issues. A simple "CatalogProvider" interface/trait would be all that was needed. It also paves the way for new features, such as #15.

Another option would be to have SDK users create a Google Guice module of custom operations, but that seems like more work for the SDK user, and more chance for an SDK users to muck with internals in an unexpected way (i.e. grabbing other resources via injection annotations).

**Comment by jaroslaw-osmanski** [comment]
Solved in current master
