### ISSUE TITLE
Provide SDK support for custom Evaluators

### ISSUE THREAD

**Issue by metasim** [deepsense-ai/seahorse#40]
`@Register` only works for `DOperation` and `Evaluator`s derive from `DOperable`.

**Comment by metasim** [comment]
An approach like #30 whereby providers are given access to the Catalog would make this easier.

**Comment by jaroslaw-osmanski** [comment]
This commit shows how to setup Evaluator in SDK: https://github.com/deepsense-ai/seahorse/commit/b0622d8853a5c41f89be477104808c6f1c679eb6
