### ISSUE TITLE
Files in `spark_applications_logs` are empty

### ISSUE THREAD

**Issue by metasim** [deepsense-ai/seahorse#43]
Seahorse appears to mount `spark_applications_logs` correctly as many files are created (even `.lck` files) but all of them have zero bytes. How do we enable logging?

**Comment by metasim** [comment]
FWIW: The impetus for needing these is that we can't connect to an external, stand-alone cluster, and need a means of debugging the problem:

<img width="298" alt="screen shot 2018-03-26 at 5 32 11 pm" src="https://user-images.githubusercontent.com/131013/37934294-b8b5eaac-311b-11e8-8b4b-30600f09ac85.png">

**Comment by mteldridge** [comment]
It looks like the SparkLauncher is not redirecting to the correct session manager logger.  Here is a PR for the fix: #49

FYI, the log configuration (https://github.com/deepsense-ai/seahorse/blob/master/seahorse-workflow-executor/commons/src/main/resources/log4j.xml) is creating two appenders.  One is the console appender which is what gets redirected in session manager.  The other is a rolling file appender that will write to the CWD of the session manager in its Docker container.  This might be problematic in that it is an AuFS volume.  My recommendation would be to turn off the file appender.
