### ISSUE TITLE
Limiting parallelism to a max of 4 is overly constrictive

### ISSUE THREAD

**Issue by metasim** [deepsense-ai/seahorse#47]
While heavy-duty users should be connecting Seahorse to a cluster, a lot can be done with it in local mode. The biggest impediment to this in our use cases is the artificial limitation on parallelism that Seahorse preemptively places on a user:

This code:
https://github.com/deepsense-ai/seahorse/blob/868b1a8563c9bcd973b95a44de4510109ead9622/sessionmanager/src/main/scala/ai/deepsense/sessionmanager/service/sessionspawner/sparklauncher/clusters/LocalSparkLauncher.scala#L55-L64

The user should be given the freedom to determine resource usage themselves, setting `spark.default.parallelism` through the "Custom Settings" box should they need to limit Spark.

**Comment by jaroslaw-osmanski** [comment]
Resolved by https://github.com/deepsense-ai/seahorse/pull/93
Add --conf spark.default.parallelism=N in local cluster settings
