### ISSUE TITLE
Can't connect to any external Spark cluster

### ISSUE THREAD

**Issue by mobsy74** [deepsense-ai/seahorse#48]
We are having trouble attaching Seahorse to any external Spark cluster.  We have tried to attach to our own internal stand-alone cluster from a Seahorse instance running on the same physical machine.  Images were built on linux and session-manager is running in host network mode.  The session-manager can see and bind to the host machine's NIC/IP.  Th Spark cluster is accessible to all other machines on the network, and regularly runs jobs.  But when we try to connect Seahorse to Spark, we get what appears to be a timeout error.

```
[WARN ] [2018-04-02 12:57:00,735] [appclient-register-master-threadpool-0]  org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint - Failed to connect to master 10.0.4.150:7077
org.apache.spark.SparkException: Exception thrown in awaitResult
	at org.apache.spark.rpc.RpcTimeout$$anonfun$1.applyOrElse(RpcTimeout.scala:77)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$1.applyOrElse(RpcTimeout.scala:75)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:59)
	at org.apache.spark.rpc.RpcTimeout$$anonfun$addMessageIfTimeout$1.applyOrElse(RpcTimeout.scala:59)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:167)
	at org.apache.spark.rpc.RpcTimeout.awaitResult(RpcTimeout.scala:83)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRefByURI(RpcEnv.scala:100)
	at org.apache.spark.rpc.RpcEnv.setupEndpointRef(RpcEnv.scala:108)
	at org.apache.spark.deploy.client.StandaloneAppClient$ClientEndpoint$$anonfun$tryRegisterAllMasters$1$$anon$1.run(StandaloneAppClient.scala:106)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

We have also tried to to set up Seahorse on an AWS host and connect it to an EMR cluster:
EMR Yarn cluster running Spark 2.1.1.
Security groups configured to allow all traffic to and from Seahorse docker host and EMR cluster machines.  Verified ping capability in both directions.
Seahorse images built on Linux and imported into AWS docker host.
/etc/hadoop/conf directory has been copied from the EMR master into the Seahorse data directory and referenced in the external cluster config.  The configs use all AWS internal IP or DNS names, which are resolvable to the Seahorse containers.
Configured with the User IP as the internal IP of the AWS docker host machine (same IP as session-manager in host network mode).
Seahorse cluster starts up fine and can run jobs in local spark context.
However, when we try to attach to the EMR cluster, it fails silently.  There are no errors in the session-manager log.  Just this message:

`WARNING: Lost connection to spark application.`

The UI shows an Execute error:

`Something went wrong, try again later. If the problem persists, please contact administrators providing them id of this workflow (152869a4-33fb-4256-a753-39423bb7fe79) and current time (2018-04-02 15:50:08).`

**Comment by mobsy74** [comment]
As an update, we were able to connect to the AWS EMR Yarn cluster.  Apparently Spark 2.1.1 has dependencies on both jersey 2 and jersey 1:

https://www.hackingnote.com/en/spark/trouble-shooting/NoClassDefFoundError-ClientConfig/

Disabling the yarn.timeline-service in yarn-site.xml allowed us to connect to the EMR cluster.  We still can't connect to our in-house Spark Standalone cluster though.

**Comment by mobsy74** [comment]
There are definitely cores and memory available on the spark cluster.  We don't have any other workflows running because we can't connect to it.  We are not setting any unusual parameters or specifying any spark classpath jars in the cluster preset...just the required values.

**Comment by anitakar** [comment]
From your comments I see that you definitely know what you are doing with your cluster, but just to rule out any trivial mistakes: does your standalone cluster spark version match seahorse spark version?

**Comment by mobsy74** [comment]
Actually they are different.  Our spark stand-alone cluster is running 2.2.1 and our version of Seahorse in 2.1.1.  Do these have to line up exactly in order for Seahorse to connect?

**Comment by anitakar** [comment]
They should. The whole seahorse codebase is compiled against some version of spark and some version of hadoop. To be honest I do not know what are the exact changes between Spark 2.1.1 and Spark 2.2.1, but it is a major release so compatibility may have been broken.

Luckily for you @jaroslaw-osmanski has already made a PR for supporting Spark 2.2 (https://github.com/deepsense-ai/seahorse/pull/65). From what I know it is in final stages of testing. You can either wait for the release or build seahorse from sources. I can also see that docker has been already released: https://quay.io/repository/deepsense_io/seahorse-workflowmanager?tag=latest&tab=tags.
