### ISSUE TITLE
Getting error when importing sklearn library in Python Notebook

### ISSUE THREAD

**Issue by courtney-whalen** [deepsense-ai/seahorse#53]
When I try running the following import in Python notebook: `from sklearn.cluster import KMeans`, I get the following error: `ImportError: libgfortran.so.1: cannot open shared object file: No such file or directory`

**Comment by jaroslaw-osmanski** [comment]
Is libgfortran.so.1 present in sessionmanager container?
Does "/opt/conda/bin/conda install libgfortran==1" in sessionmanger help?
Is it Seahorse 1.4.3 ?

**Comment by courtney-whalen** [comment]
Running this code in the jupyter notebook fixes the ImportError:

`import sys
!{sys.executable} -m conda install -y libgfortran==1`

**Comment by courtney-whalen** [comment]
Yes, it's Seahorse 1.4.3

**Comment by mobsy74** [comment]
@jaroslaw-osmanski Yes, installing libgfortran on the sessionmanager fixes this issue. We just added the following line to the sessionmanager/docker.sbt file:

**Comment by jaroslaw-osmanski** [comment]
This should fix it:
https://github.com/deepsense-ai/seahorse/pull/56
