### ISSUE TITLE
Provide ability to view full text of truncated report cells

### ISSUE THREAD

**Issue by metasim** [deepsense-ai/seahorse#59]
This code...

https://github.com/deepsense-ai/seahorse/blob/54e1b5999dc4f397197851a0857abe44e142bf26/frontend/client/app/workflows/reports/report-table/report-table.controller.js#L68-L73

...and its call site...

https://github.com/deepsense-ai/seahorse/blob/54e1b5999dc4f397197851a0857abe44e142bf26/frontend/client/app/workflows/reports/report-table/report-table.html#L38

...truncate potentially important information without a mechanism for easily drilling down, exporting, and/or copying the actual value. There is an attempt to show this information in a tool tip, but the size of the tool tip is constrained and the text spills over and overlaps with the text underneath it.

One option would be to add a "View..." link and show full text in a modal window in a monospaced font, and allow for text selection/copying.

**Comment by jaroslaw-osmanski** [comment]
Resolved in https://github.com/deepsense-ai/seahorse/pull/94
