### ISSUE TITLE
docker-compose up get connection error

### ISSUE THREAD

**Issue by bleachzk** [deepsense-ai/seahorse#6]
proxy_1              | GET /v1/sessions - - ms - -
proxy_1              | { Error: connect EHOSTUNREACH 10.255.3.1:9082
proxy_1              |     at Object.exports._errnoException (util.js:1020:11)
proxy_1              |     at exports._exceptionWithHostPort (util.js:1043:20)
proxy_1              |     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
proxy_1              |   code: 'EHOSTUNREACH',
proxy_1              |   errno: 'EHOSTUNREACH',
proxy_1              |   syscall: 'connect',
proxy_1              |   address: '10.255.3.1',
proxy_1              |   port: 9082 }

**Comment by jaroslaw-osmanski** [comment]
Does this problem still affect you? Is it present in 1.4.2?
