### ISSUE TITLE
Report "Close" button scrolls off screen when scrolling report table

### ISSUE THREAD

**Issue by metasim** [deepsense-ai/seahorse#60]
The report area appropriately scrolls overflow content:

<img width="386" alt="screen shot 2018-05-01 at 10 00 09 am" src="https://user-images.githubusercontent.com/131013/39475601-d9e52f5e-4d26-11e8-9464-ba6382ec6448.png">

but the "Close" button scrolls off view along with the report content, making it more troublesome to close the report after reviewing content:

<img width="412" alt="screen shot 2018-05-01 at 10 00 17 am" src="https://user-images.githubusercontent.com/131013/39475660-0cf9a276-4d27-11e8-97fd-adda68083ec4.png">

**Comment by anitakar** [comment]
If you click inside data table, you will use inner table scroll and close button will stay in place.
![another_scrollbar](https://user-images.githubusercontent.com/4841572/39809577-77c17190-5382-11e8-9fb9-300bf9ebf8d6.png)

**Comment by jaroslaw-osmanski** [comment]
Resolved by https://github.com/deepsense-ai/seahorse/pull/94
