### ISSUE TITLE
Feature request: read data from Hadoop files / Custom data sources

### ISSUE THREAD

**Issue by rabejens** [deepsense-ai/seahorse#7]
In my application, I have to read data in a lot of exotic formats, sometimes binary, but never usable with the possibilities Seahorse offers (CSV, JSON, Parquet). It is measuring data from proprietary measuring devices that isn't to be converted prior to analyzing.
For this, I use Hadoop's `FileInputFormat` classes, Spark's `newAPIHadoopFile` function and some `map`ping to get the stuff into Spark.

It would be nice if Seahorse supported something like this. My proposal would be:

- Specify a custom JAR file with the reading logic as when using JDBC
- Have a well-defined method somewhere in the JAR (similar to the `main` method) which takes the `SparkContext` and additional parameters, and spits out a `DataFrame`

**Comment by witold-jedrzejewski-codilime** [comment]
For now, this can be done using SDK - https://github.com/deepsense-ai/seahorse-sdk-example/tree/1.4.1

**Comment by rabejens** [comment]
The SDK is unfortunately out of date. See the issue I posted there.

**Comment by jaroslaw-osmanski** [comment]
SDK should work now. @rabejens can you confirm that?

**Comment by rabejens** [comment]
I am currently not near one of my computers but I try it tomorrow.

**Comment by rabejens** [comment]
OK, I just tried it and the example compiled fine (apart from tests failing).
